baseURL = "https://nextworklab.co.kr/"
languageCode = "en-us"
title = "NextWork Lab."

[params]
  description = "제품 소개 및 사용설명서"

[menu]
  [[menu.main]]
    name = "소개"
    url = "#about"
    weight = 10

  [[menu.main]]
    name = "신체기능"
    url = "#function"
    weight = 20

  [[menu.main]]
    name = "안전한 작업"
    url = "#safework"
    weight = 30

  [[menu.main]]
    name = "Contact"
    url = "#contact"
    weight = 40
