[menu]
  [[menu.main]]
    name = "About"
    url = "#about"
    weight = 10

  [[menu.main]]
    name = "CBW"
    url = "#cbw"
    weight = 20

  [[menu.main]]
    name = "exgel"
    url = "#exgel"
    weight = 30

  [[menu.main]]
    name = "Contact"
    url = "#contact"
    weight = 40
